hostel_Management/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('management.urls'))

]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

management/urls.py
from django.urls import path, include
from . import views
from django.conf import settings
from django.conf.urls.static import static


app_name = 'management'

urlpatterns = [
    path('', views.signin, name='signin'),
    path('room_change_request/', views.roomChangeRequest, name='roomChangeRequest'),
    path('menu/', views.menu, name='menu'),
    path('feedback/', views.feedback, name='feedback'),
    path('complaint/', views.complaint, name='complaint'),
    path('profile/', views.profile, name='profile'),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

management/models.py
from django.contrib.auth.models import User #importing django's inbuilt user Model
from django.db import models
from django.utils import timezone
#This models file is used to define the tables i.e. database schema
#here none of the primary keys have been defined by developers but django's automatic primary key generation has been used
#to specify a custom primary key in place of automatically generated one, specify primary_key=True on the required  field.
class Hostel(models.Model):
    hostel_number = models.CharField(max_length=2, null=False)
    warden = models.CharField(max_length=30, null=False)

    def __str__(self):
        val = "Hostel - " + str(self.hostel_number)
        return val


class Room(models.Model):
    hostel = models.ForeignKey(Hostel, on_delete=models.CASCADE, null=False) #Foreign key relationship
    room_num = models.IntegerField(null=False)
    wing = models.CharField(max_length=1, null=False)
    floor = models.IntegerField(null=False)
    capacity = models.IntegerField(null=False)
    status = models.IntegerField(null=False, default=0)

    def __str__(self):
        val = '-'.join([self.hostel.hostel_number, self.wing, str(self.floor*100 + self.room_num)])
        return val


class Student(models.Model):
    roll_num = models.ForeignKey(User, Room, null=False, db_column="username", unique=True)
    first_name = models.CharField(max_length=20, null=False)
    last_name = models.CharField(max_length=20, null=False)
    mail = models.CharField(max_length=30, null=False)
    student_contact_num = models.BigIntegerField(null=False)
    guardian_contact_num = models.BigIntegerField(null=False)
    gender = models.CharField(max_length=1, null=False)
    room = models.ForeignKey(Room, on_delete=models.CASCADE, null=False)

    def __str__(self):
        val = self.roll_num.username + '-' + self.first_name + '_' + self.last_name
        return val


class Feedback(models.Model):
    hostel = models.ForeignKey(Hostel, on_delete=models.CASCADE)
    feedback = models.CharField(max_length=255)
    date = models.DateField(default=timezone.now)


class Complaint(models.Model):
    student = models.ForeignKey(Student, on_delete=models.CASCADE, null=False)
    complaint = models.CharField(max_length=255)
    date = models.DateField(default=timezone.now)


class ChangeRoom(models.Model):
    student = models.ForeignKey(Student, on_delete=models.CASCADE, null=False)
    reason = models.CharField(max_length=255)
    date = models.DateField(default=timezone.now)

class Attendance(models.Model):
    txtReport = models.FileField(upload_to='static/AttendanceRecords', null=False)
    date = models.DateField(null=False)

management/views.py
from django.contrib.auth.models import User
from django.http import HttpResponseRedirect
from django.http import FileResponse
from django.shortcuts import render, HttpResponse, redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from .models import *


@login_required
def menu(request):
    return render(request, 'student/menu.html', {})


def signin(request):

    if request.user.is_authenticated:
        logout(request)
        messages.success(request, "You are Logged out")
        return signin(request)
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']

        user = authenticate(username=username, password=password)

        if user is not None and user.is_superuser == 0:
            login(request, user)
            return menu(request)

        else:
            messages.error(request, "Invalid username or password")

    return render(request, 'signin.html', {})


@login_required
def profile(request):

    if request.method == 'POST':
        if request.POST['password1'] == request.POST['password2']:
            user = User.objects.get(username=request.user.username)
            user.set_password(request.POST['password1'])
            user.save()
            messages.success(request, "Password updated.\n Log in again with new password")
            return render(request, 'signin.html', {})
    user = Student.objects.get(roll_num=request.user.id)
    context = {'roll_num': user.roll_num, 'name':str(user.first_name) + ' ' + str(user.last_name), 'mail':user.mail, 'student_contact_num':user.student_contact_num, 'guardian_contact_num':user.guardian_contact_num, 'room':user.room}
    print(context)
    return render(request, 'student/profile.html', context)





@login_required
def roomChangeRequest(request):

    if request.method == 'POST':
        reason = ChangeRoom()
        reason.reason = request.POST['reason']
        reason.student = Student.objects.get(roll_num=request.user.id)
        reason.save()
        messages.success(request, "Request submitted succesfully.")

    return render(request, 'student/room_change_request.html', {})


@login_required
def feedback(request):

    if request.method == 'POST':
        feedback = Feedback()
        feedback.feedback = request.POST['feedback']
        feedback.hostel = Student.objects.get(roll_num=request.user.id).room.hostel
        feedback.save()
        messages.success(request, "Feedback submitted succesfully.")

    return render(request, 'student/feedback.html', {})


@login_required
def complaint(request):

    if request.method == 'POST':
        complaint = Complaint()
        complaint.complaint = request.POST['complaint']
        complaint.student = Student.objects.get(roll_num=request.user.id)
        complaint.save()
        messages.success(request, "Complaint registered succesfully.")

    return render(request, 'student/complaint.html', {})

templates/nav_bar.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link rel="icon" href="https://admissions.lnmiit.ac.in/assets/img/gallery/big/BOYS%20HOSTEL%203.jpg">
    <title>LNM Hostel-Management</title>
    <style>
    body{

    background-image:url('https://admissions.lnmiit.ac.in/assets/img/gallery/big/BOYS%20HOSTEL%203.jpg');
    background-repeat:no-repeat;
    background-attachment:fixed;
    background-size: 100% 100%;

    }
    </style>
  </head>
  <body >

  <!-- Navbar -->
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <!-- Container wrapper -->
  <div class="container">
    <!-- Navbar brand -->
    <a class="navbar-brand me-2" href="{% url 'management:menu' %}">
    LNM Hostel-Management
    </a>

    <!-- Toggle button -->
    <button
      class="navbar-toggler"
      type="button"
      data-mdb-toggle="collapse"
      data-mdb-target="#navbarButtonsExample"
      aria-controls="navbarButtonsExample"
      aria-expanded="false"
      aria-label="Toggle navigation"
    >
      <i class="fas fa-bars"></i>
    </button>

    <!-- Collapsible wrapper -->
    <div class="collapse navbar-collapse" id="navbarButtonsExample">

      <div class="d-flex align-items-center">
        <a class="nav-link" href="{% url 'management:profile' %}">
        <button type="button" class="btn btn-link px-3 me-2" style="text-decoration: none !important;">
          {{ user.username }}
        </button>
      </a>
        <a href="..{% url 'management:signin' %}">
        <button type="button" class="btn btn-primary me-3">

          Logout

        </button>
        </a>
      </div>
    </div>
    <!-- Collapsible wrapper -->
  </div>
  <!-- Container wrapper -->
</nav>

<!-- Navbar -->

    <main class="container">
        {% block content %}
        {% endblock %}
    </main>

  </body>
</html>

templates/signin.html
<!doctype html>
<html lang="en">
<head>
	<title>LNM Hostel-Management</title>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	<link rel="icon" href="https://admissions.lnmiit.ac.in/assets/img/gallery/big/BOYS%20HOSTEL%203.jpg">
	<link href="https://fonts.googleapis.com/css?family=Lato:300,400,700&display=swap" rel="stylesheet">
	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
		integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
</head>
<style>
	.button {
		background-color: #008CBA;
		/* Green */
		border: none;
		color: white;
		padding: 10px 20px;
		text-align: center;
		text-decoration: none;
		display: inline-block;
		font-size: 16px;
		margin: 4px 2px;
		transition-duration: 0.4s;
		cursor: pointer;
	}
	body{

    background-image:url('https://admissions.lnmiit.ac.in/assets/img/gallery/big/BOYS%20HOSTEL%203.jpg');
    background-repeat:no-repeat;
    background-attachment:fixed;
    background-size: 100% 100%;

    }

</style>

<body>



	<div class="container">
		<div class="col-lg-10 text-center mx-auto m-3 p-3">
			<p class="display-6"><b>LNM Hostel-Management</b></p>
		</div>
		<div class="row justify-content-center " >
			<div class="col-md-6 col-lg-4" style="border:3px solid #dc3545;background-color: white;">
				<br/>
				<div class="login-wrap p-3">
					{% for message in messages %}
					<div class="alert alert-danger">{{message}}</div>
					{% endfor %}
					<form action="{% url 'management:signin' %}" class="signin-form" method="POST">

						{% csrf_token %}
						<div class="form-group mb-3 p-2">
							<input type="text" name="username" class="form-control" placeholder="Username" required>
						</div>
						<div class="form-group mb-3 p-2">
							<input id="password-field" type="password" class="form-control " placeholder="Password"
								name="password" required>
							<span toggle="#password-field" class="fa fa-fw fa-eye field-icon toggle-password"></span>
						</div>
						<div class="form-group">
							<button type="submit"
								class=" form-control btn btn-success btn-lg border rounded btn-danger">Sign
								In</button>
						</div>

						<br/>
					</form>
					<a href="admin/"><button type="submit"
								class=" form-control btn btn-success btn-lg border rounded btn-danger">Sign In as admin</button></a>
				</div>
			</div>
		</div>
	</div>



</body>

</html>

templates/student/complaint.html
{% extends "nav_bar.html" %}

{% block content %}



<style>
.contact-form {
	position: absolute;
	top: 50%;
	left: 50%;
	transform: translate(-50%, -50%);

	padding: 80px 40px;
	background: rgba(0, 0, 0, 0.5);
}
.avatar {
	position: absolute;
	width: 80px;
	height: 80px;
	border-radius: 50%;
	overflow: hidden;
	top: calc(-80px/2);
	left: 190px;
}
.contact-form h2 {
	margin: 0;
	padding: 0 0 20px;
	color: #fff;
	text-align: center;
	text-transform: uppercase;
}
.contact-form p {
	margin: 0;
	padding: 0;
	font-weight: bold;
	color: #fff;
}
.contact-form input {
	width: 100%;
	margin-bottom: 20px;
}
.contact-form .a{
	width:100%;
	padding:5px;
	margin-bottom:20px;
}

.contact-form input[type=button]
{
	height: 30px;
	color: #fff;
	font-size: 15px;
	background: red;
	cursor: pointer;
	border-radius: 25px;
	border: none;
	outline: none;
	margin-top: 2%;
  z-index: 0;
}

.contact-form a
{
	color: #fff;
	font-size: 14px;
	font-weight: bold;
	text-decoration: none;
}


.tooltip {
  position: relative;

}

.tooltip .tooltiptext {
  visibility: hidden;
  background-color: #555;
  color: #fff;
  text-align: center;
  border-radius: 6px;
  padding: 5px 0px;
  position: absolute;
  z-index: 1;
  opacity: 0;
  transition: opacity 0.3s;
}

.tooltip .tooltiptext::after {
  content: "";
  position: relative;
  top: 100%;
  left: 70%;
  margin-left: 5px;
  border-width: 5px;
  border-style: solid;
  border-color: #555 transparent transparent transparent;
}

.tooltip:hover .tooltiptext {
  visibility: visible;
  opacity: 1;
}

.admin{
	padding:10px;
	border:black;
}
#heading{
	color:white;
}

.table{
	color:white;
}
</style>



<div class="contact-form">
      <h2 >Complaints</h2>
	  {% for message in messages %}
	  <div class="alert alert-danger">{{message}}</div>
	  {% endfor %}
      <form method="post" action="{% url 'management:complaint' %}">
        {% csrf_token %}
      <p> <textarea class="form-control" rows="4" cols="50" id="complaint" name="complaint" style=" resize: none" placeholder="Type your complaint here ..." required></textarea> </p>
        <br/>
    <input name="submit" value="submit" type="submit" class="btn btn-danger btn-block">
    </form>

</div>




{% endblock %}

templates/student/feedback.html
{% extends "nav_bar.html" %}

{% block content %}

<style>
.contact-form {
	position: absolute;
	top: 50%;
	left: 50%;
	transform: translate(-50%, -50%);

	padding: 80px 40px;
	background: rgba(0, 0, 0, 0.5);
}
.avatar {
	position: absolute;
	width: 80px;
	height: 80px;
	border-radius: 50%;
	overflow: hidden;
	top: calc(-80px/2);
	left: 190px;
}
.contact-form h2 {
	margin: 0;
	padding: 0 0 20px;
	color: #fff;
	text-align: center;
	text-transform: uppercase;
}
.contact-form p {
	margin: 0;
	padding: 0;
	font-weight: bold;
	color: #fff;
}
.contact-form input {
	width: 100%;
	margin-bottom: 20px;
}
.contact-form .a{
	width:100%;
	padding:5px;
	margin-bottom:20px;
}

.contact-form input[type=button]
{
	height: 30px;
	color: #fff;
	font-size: 15px;
	background: red;
	cursor: pointer;
	border-radius: 25px;
	border: none;
	outline: none;
	margin-top: 2%;
  z-index: 0;
}

.contact-form a
{
	color: #fff;
	font-size: 14px;
	font-weight: bold;
	text-decoration: none;
}


.tooltip {
  position: relative;

}

.tooltip .tooltiptext {
  visibility: hidden;
  background-color: #555;
  color: #fff;
  text-align: center;
  border-radius: 6px;
  padding: 5px 0px;
  position: absolute;
  z-index: 1;
  opacity: 0;
  transition: opacity 0.3s;
}

.tooltip .tooltiptext::after {
  content: "";
  position: relative;
  top: 100%;
  left: 70%;
  margin-left: 5px;
  border-width: 5px;
  border-style: solid;
  border-color: #555 transparent transparent transparent;
}

.tooltip:hover .tooltiptext {
  visibility: visible;
  opacity: 1;
}

.admin{
	padding:10px;
	border:black;
}
#heading{
	color:white;
}

.table{
	color:white;
}
</style>



<div class="contact-form">
      	<h2 >Feedback</h2>
	 	{% for message in messages %}
		<div class="alert alert-danger">{{message}}</div>
		{% endfor %}	
        <form method="post" action="{% url 'management:feedback' %}">
        {% csrf_token %}
      	<p> <textarea class="form-control" rows="4" cols="50" id="feedback" name="feedback" style=" resize: none" placeholder="Type your feedback here ..." required></textarea> </p>
        <br/>
    <input name="submit" value="submit" type="submit" class="btn btn-danger btn-block">
    </form>

</div>





{% endblock %}

templates/student/menu.html
{% extends "nav_bar.html" %}

{% block content %}
<style>
.contact-form {
	position: absolute;
	top: 50%;
	left: 50%;
	transform: translate(-50%, -50%);

	padding: 80px 40px;
	background: rgba(0, 0, 0, 0.5);
}
.avatar {
	position: absolute;
	width: 80px;
	height: 80px;
	border-radius: 50%;
	overflow: hidden;
	top: calc(-80px/2);
	left: 190px;
}
.contact-form h2 {
	margin: 0;
	padding: 0 0 50px;
	color: #fff;
	text-align: center;
	text-transform: uppercase;
}
.contact-form p {
	margin: 0;
	padding: 0;
	font-weight: bold;
	color: #fff;
}
.contact-form input {
	width: 100%;
	margin-bottom: 20px;
}
.contact-form .a{
	width:100%;
	padding:5px;
	margin-bottom:20px;
}

.contact-form input[type=button]
{
	height: 30px;
	color: #fff;
	font-size: 15px;
	background: red;
	cursor: pointer;
	border-radius: 25px;
	border: none;
	outline: none;
	margin-top: 2%;
  z-index: 0;
}

.contact-form a
{
	color: #fff;
	font-size: 14px;
	font-weight: bold;
	text-decoration: none;
}


.tooltip {
  position: relative;

}

.tooltip .tooltiptext {
  visibility: hidden;
  background-color: #555;
  color: #fff;
  text-align: center;
  border-radius: 6px;
  padding: 5px 0px;
  position: absolute;
  z-index: 1;
  opacity: 0;
  transition: opacity 0.3s;
}

.tooltip .tooltiptext::after {
  content: "";
  position: relative;
  top: 100%;
  left: 70%;
  margin-left: 5px;
  border-width: 5px;
  border-style: solid;
  border-color: #555 transparent transparent transparent;
}

.tooltip:hover .tooltiptext {
  visibility: visible;
  opacity: 1;
}

.admin{
	padding:10px;
	border:black;
}
#heading{
	color:white;
}

.table{
	color:white;
}
</style>

    <div class="contact-form"><br/>
      <h2>&nbsp;STUDENT MENU</h2>
      <div class="admin"> <a class="btn btn-danger btn-block" href="{% url 'management:roomChangeRequest' %}">Request
          room change</a> </div>
      <div class="admin"> <a href="{% url 'management:feedback' %}" name="Feedback" class="btn btn-danger btn-block">Student
          Feedback</a> </div>
      <div class="admin"> <a href="{% url 'management:complaint' %}" name="Complaints" class="btn btn-danger btn-block">Hostel
          Complaints</a> </div>
    </div>
</div>
{% endblock %}

templates/student/profile.html
{% extends "nav_bar.html" %}
{% load static %}
{% block content %}
<style>
  input::-webkit-outer-spin-button,
  input::-webkit-inner-spin-button {
    -webkit-appearance: none;
    margin: 0;
  }

  input[type=text],
  select {
    width: 100%;
    padding: 12px 30px;
    margin: 8px 0;
    display: inline-block;
    border: 1px solid #dc3545;
    border-radius: 4px;
    box-sizing: border-box;
  }

  input[type=number],
  select {
    width: 100%;
    padding: 12px 20px;
    margin: 8px 0;
    display: inline-block;
    border: 1px solid #dc3545;
    border-radius: 4px;
    box-sizing: border-box;
  }

    input[type=password],
  select {
    width: 100%;
    padding: 12px 20px;
    margin: 8px 0;
    display: inline-block;
    border: 1px solid #dc3545;
    border-radius: 4px;
    box-sizing: border-box;
  }



  input[type=submit] {
    width: 108%;
    background-color: #dc3545;
    ;
    border: none;
    color: white;
    padding: 16px 32px;
    text-align: center;
    font-size: 16px;
    margin: 40px -15px;
    opacity: 1;
    transition: 0.3s;
    display: inline-block;
    text-decoration: none;
    cursor: pointer;
  }

  input[type=submit]:hover {
    opacity: 0.7;
  }

  #content-wrapper {
    width: 100%;
    padding: 15px;
    padding-left: 345px;
  }



</style>

  <div id="wrapper">

    <div id="content-wrapper">

      <div class="container-fluid">

        <div class="row">

          <div class="col-lg-7">

            <div class="row mx-auto">
              <div class="col-lg-12" style="border:3px solid #dc3545;background-color: white;">
              <h1 class="d-flex justify-content-center">Your Profile <i class="fas fa-comment-medical ms-3 p-1"></i>
              </h1><br/>
              <div style="padding: 30px 15px;">
                <form method="POST" action="{% url 'management:profile' %}">
                  {% csrf_token %}
                  <div>
                        <label for="roll_num" class="labels">Roll Number</label><br/>
                  <input type="text" id="roll_num" name="roll_num" value='{{roll_num}}' readonly>&nbsp;
                  </div>

                  <div>
                        <label for="name" class="labels">Name</label><br/>
                  <input type="text" id="name" name="name" value='{{name}}' readonly>&nbsp;
                  </div>

                  <div>
                        <label for="mail" class="labels">Email</label><br/>
                  <input type="text" id="mail" name="mail" value='{{mail}}' readonly>&nbsp;
                  </div>

                  <div>
                        <label for="room_num" class="labels">Room</label><br/>
                  <input type="text" id="room_num" name="room_num" value='{{room}}' readonly>&nbsp;
                  </div>

                  <div>
                        <label for="student_contact_num" class="labels">Student's Contact Number</label><br/>
                  <input type="number" id="student_contact_num" name="student_contact_num" value={{student_contact_num}} readonly>&nbsp;
                  </div>

                  <div>
                        <label for="guardian_contact_num" class="labels">Guardian's Contact Number</label><br/>
                  <input type="number" id="guardian_contact_num" name="guardian_contact_num" value={{guardian_contact_num}} readonly>&nbsp;
                  </div>

                  <div>
                        <label for="password1" class="labels">New Password</label><br/>
                  <input type="password" id="password1" name="password1" required>&nbsp;
                  </div>
                  <div>
                        <label for="password2" class="labels">Confirm Password</label><br/>
                  <input type="password" id="password2" name="password2" required>&nbsp;
                  </div>
                  <div>
                  <input type="submit" value="SAVE CHANGES">
                  </div>
                </form>
              </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>

  </div>
{% endblock %}

templates/student/room_change_request.html
{% extends "nav_bar.html" %}

{% block content %}

<style>
.contact-form {
	position: absolute;
	top: 50%;
	left: 50%;
	transform: translate(-50%, -50%);

	padding: 80px 40px;
	background: rgba(0, 0, 0, 0.5);
}
.avatar {
	position: absolute;
	width: 80px;
	height: 80px;
	border-radius: 50%;
	overflow: hidden;
	top: calc(-80px/2);
	left: 190px;
}
.contact-form h2 {
	margin: 0;
	padding: 0 0 20px;
	color: #fff;
	text-align: center;
	text-transform: uppercase;
}
.contact-form p {
	margin: 0;
	padding: 0;
	font-weight: bold;
	color: #fff;
}
.contact-form input {
	width: 100%;
	margin-bottom: 20px;
}
.contact-form .a{
	width:100%;
	padding:5px;
	margin-bottom:20px;
}

.contact-form input[type=button]
{
	height: 30px;
	color: #fff;
	font-size: 15px;
	background: red;
	cursor: pointer;
	border-radius: 25px;
	border: none;
	outline: none;
	margin-top: 2%;
  z-index: 0;
}

.contact-form a
{
	color: #fff;
	font-size: 14px;
	font-weight: bold;
	text-decoration: none;
}


.tooltip {
  position: relative;

}

.tooltip .tooltiptext {
  visibility: hidden;
  background-color: #555;
  color: #fff;
  text-align: center;
  border-radius: 6px;
  padding: 5px 0px;
  position: absolute;
  z-index: 1;
  opacity: 0;
  transition: opacity 0.3s;
}

.tooltip .tooltiptext::after {
  content: "";
  position: relative;
  top: 100%;
  left: 70%;
  margin-left: 5px;
  border-width: 5px;
  border-style: solid;
  border-color: #555 transparent transparent transparent;
}

.tooltip:hover .tooltiptext {
  visibility: visible;
  opacity: 1;
}

.admin{
	padding:10px;
	border:black;
}
#heading{
	color:white;
}

.table{
	color:white;
}
</style>



<div class="contact-form">
      <h2 >Apply Room change</h2>
	  {% for message in messages %}
		<div class="alert alert-danger">{{message}}</div>
		{% endfor %}
    <form method="post" action="{% url 'management:roomChangeRequest' %}">
        {% csrf_token %}
      <p> <textarea class="form-control" rows="4" cols="50" id="reason" name="reason" style=" resize: none" placeholder="Type your reason for room change here ..." required></textarea> </p>
        <br/>
    <input name="submit" value="submit" type="submit" class="btn btn-danger btn-block">
    </form>

</div>


{% endblock %}